-- AlterTable
ALTER TABLE "public"."Settings" ALTER COLUMN "pointsPerDollar" SET DEFAULT 10,
ALTER COLUMN "pointsPerDollar" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "pointsPerIQD" SET DEFAULT 1,
ALTER COLUMN "pointsPerIQD" SET DATA TYPE DOUBLE PRECISION;
